### ISSUE TITLE
how to pass null Ptr

### ISSUE THREAD

**Issue by extrawurst** [twistedfall/opencv-rust#213] opened 2021-02-19 17:45 UTC
I have a stupid question:

how do I pass the C's `null` into a rust wrapper that takes `Ptr`?

example: 
```
let edge_detect =
        ximgproc::create_structured_edge_detection("model.yml", ...).unwrap();
```

the std lib `null()` seems not to be compatible.

**Comment by twistedfall** [comment] 2021-02-21 07:17
You should be able to use `from_raw` function, something like this:
```rust
    let ptr_null = unsafe { Ptr::from_raw(std::ptr::null_mut()) };
    ximgproc::create_structured_edge_detection("model.yml", ptr_null);
```

**Comment by extrawurst** [comment] 2021-02-22 16:31
the key missing element for this to work is:
```
use opencv::prelude::Boxed;
```

but anyhow this seg faults even though `NULL` is supposed to be a valid param here :(

**Comment by twistedfall** [comment] 2021-02-22 17:03
I wonder whether the segfault is happening because of the bindings or OpenCV. Do you have more details?

**Comment by twistedfall** [comment] 2021-02-26 10:17
If you could also provide the minimal reproducible example I could also check it out.

**Comment by sumibi-yakitori** [comment] 2022-09-07 05:37
I am having the exact same problem. It occurs with the following code.
The execution environment is MacOS and OpenCV is installed from homebrew.

opencv: stable 4.6.0 (bottled)

```rust
let ptr_null = unsafe { Ptr::from_raw(core::ptr::null_mut()) };
let path = Path::new("model.yml");
if path.exists() {
  let edge_detector = ximgproc::create_structured_edge_detection(&path.to_string_lossy(), ptr_null)?;
}
```

**Comment by twistedfall** [comment] 2022-09-07 05:47
Let me check this out. Can you also share the corresponding `model.yml`?

**Comment by sumibi-yakitori** [comment] 2022-09-07 06:04
@twistedfall 
Thanks for the quick reply!
https://github.com/opencv/opencv_extra/blob/4.x/testdata/cv/ximgproc/model.yml.gz
I am using this file. Of course I unzip and use it.
(Incidentally, it did not make sense to make the path to the model file an absolute path)

However, it seems that the same SIGSEGV occurs when I specify the path to a model file that does not exist.

```
(signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by sumibi-yakitori** [comment] 2022-09-07 06:55
I tried to run that code in Manjaro, but got the same error.

**Comment by sumibi-yakitori** [comment] 2022-09-10 00:34
This C++ code worked fine on my MacOS, so maybe it is the bindings issue.

```cpp
#include <opencv2/opencv.hpp>
#include <opencv2/ximgproc.hpp>

using namespace cv;
using namespace cv::ximgproc;

int main() {
  auto pDetector = createStructuredEdgeDetection("model.yml");

  return 0;
}
```

**Comment by twistedfall** [comment] 2022-09-17 11:41
Fixed in v0.68.0, you can now pass `None` to that function

**Closed as completed by twistedfall** 2022-09-17 11:41 UTC
