### ISSUE TITLE
Can't join thread: Any

### ISSUE THREAD

**Issue by yang-dong-dong** [twistedfall/opencv-rust#227] opened 2021-04-15 04:34 UTC
1. mocOS 10.15.7
2. brew install 
3. 0.52.0
4. rustc 1.52.0-nightly (e37a13cc3 2021-02-28)

![image](https://user-images.githubusercontent.com/20069609/114814320-88e9e180-9de6-11eb-9ff7-cf59ae4d65be.png)

![image](https://user-images.githubusercontent.com/20069609/114814303-7f607980-9de6-11eb-9e15-43d7d1f2fdfd.png)

**Comment by twistedfall** [comment] 2021-04-15 04:59
I would need a full build log as produced by `cargo build -vv` to be able to help.

**Comment by yang-dong-dong** [comment] 2021-04-15 07:07
Fresh unicode-xid v0.2.1
       Fresh cfg-if v1.0.0
       Fresh ucd-trie v0.1.3
       Fresh maplit v1.0.2
       Fresh matches v0.1.8
       Fresh autocfg v1.0.1
       Fresh tinyvec_macros v0.1.0
       Fresh percent-encoding v2.1.0
       Fresh regex-syntax v0.6.23
       Fresh lazy_static v1.4.0
       Fresh version_check v0.1.5
       Fresh glob v0.3.0
       Fresh itoa v0.4.7
       Fresh same-file v1.0.6
       Fresh cookie-factory v0.2.4
       Fresh semver-parser v0.7.0
       Fresh quick-error v1.2.3
       Fresh ppv-lite86 v0.2.10
       Fresh once_cell v1.7.2
       Fresh dunce v1.0.1
       Fresh cfg-if v0.1.10
       Fresh pkg-config v0.3.19
       Fresh shlex v1.0.0
       Fresh percent-encoding v1.0.1
       Fresh slab v0.4.2
       Fresh vcpkg v0.2.11
       Fresh remove_dir_all v0.5.3
       Fresh bytes v0.5.6
       Fresh lazycell v1.3.0
       Fresh hashbrown v0.9.1
       Fresh pest v2.1.3
       Fresh tinyvec v1.2.0
       Fresh unicode-bidi v0.3.5
       Fresh walkdir v2.3.2
       Fresh form_urlencoded v1.0.1
       Fresh libc v0.2.93
       Fresh proc-macro2 v1.0.26
       Fresh input_buffer v0.3.1
       Fresh memchr v2.3.4
       Fresh unicode-normalization v0.1.17
       Fresh log v0.4.14
       Fresh ryu v1.0.5
       Fresh pest_meta v2.1.3
       Fresh semver-parser v0.10.2
       Fresh quote v1.0.9
       Fresh aho-corasick v0.7.15
       Fresh idna v0.2.2
       Fresh getrandom v0.2.2
       Fresh core-foundation-sys v0.8.2
       Fresh jobserver v0.1.21
       Fresh idna v0.1.5
       Fresh net2 v0.2.37
       Fresh bitflags v1.2.1
       Fresh iovec v0.1.4
       Fresh doc-comment v0.3.3
       Fresh syn v1.0.69
       Fresh regex v1.4.5
       Fresh nom v4.2.3
       Fresh clang-sys v1.2.0
       Fresh url v2.2.1
       Fresh semver v0.11.0
       Fresh crossbeam-utils v0.8.3
       Fresh indexmap v1.6.2
       Fresh num-traits v0.2.14
       Fresh serde_derive v1.0.125
       Fresh pest_generator v2.1.3
       Fresh rand_core v0.6.2
       Fresh clang v1.0.3
       Fresh core-foundation v0.9.1
       Fresh security-framework-sys v2.2.0
       Fresh cc v1.0.67
       Fresh snafu-derive v0.6.10
       Fresh mio v0.6.23
       Fresh url v1.7.2
       Fresh serde v1.0.125
       Fresh pest_derive v2.1.0
       Fresh rand_chacha v0.3.0
       Fresh opencv-binding-generator v0.26.0
       Fresh security-framework v2.2.0
       Fresh crossbeam-channel v0.5.0
       Fresh serde_json v1.0.64
       Fresh toml v0.5.8
       Fresh semver v0.9.0
       Fresh rand v0.8.3
       Fresh mio-extras v2.0.6
       Fresh snafu v0.6.10
       Fresh handlebars v1.1.0
       Fresh amq-protocol-types v1.2.0
       Fresh cargo-lock v4.0.1
       Fresh tempfile v3.2.0
   Compiling opencv v0.52.0
       Fresh amq-protocol-codegen v1.4.0
       Fresh built v0.4.4
       Fresh native-tls v0.2.7
     Running `/Library/Stacks/development/rust/workspace/sak_tools/target/debug/build/opencv-0af03f55ee6b47bf/build-script-build`
       Fresh amq-protocol v1.4.0
       Fresh amiquip v0.4.0
[opencv 0.52.0] === Crate version: Some("0.52.0")
[opencv 0.52.0] === Environment configuration:
[opencv 0.52.0] ===   OPENCV_HEADER_DIR = None
[opencv 0.52.0] ===   OPENCV_PACKAGE_NAME = None
[opencv 0.52.0] ===   OPENCV_PKGCONFIG_NAME = None
[opencv 0.52.0] ===   OPENCV_CMAKE_NAME = None
[opencv 0.52.0] ===   OPENCV_CMAKE_BIN = None
[opencv 0.52.0] ===   OPENCV_VCPKG_NAME = None
[opencv 0.52.0] ===   OPENCV_LINK_LIBS = None
[opencv 0.52.0] ===   OPENCV_LINK_PATHS = None
[opencv 0.52.0] ===   OPENCV_INCLUDE_PATHS = None
[opencv 0.52.0] ===   OPENCV_DISABLE_PROBES = None
[opencv 0.52.0] ===   OPENCV_CLANG_STDLIB_PATH = None
[opencv 0.52.0] ===   OPENCV_MODULE_WHITELIST = None
[opencv 0.52.0] ===   OPENCV_MODULE_BLACKLIST = None
[opencv 0.52.0] ===   CMAKE_PREFIX_PATH = None
[opencv 0.52.0] ===   OpenCV_DIR = None
[opencv 0.52.0] ===   PKG_CONFIG_PATH = None
[opencv 0.52.0] ===   VCPKG_ROOT = None
[opencv 0.52.0] ===   VCPKGRS_DYNAMIC = None
[opencv 0.52.0] === Enabled features:
[opencv 0.52.0] ===   BINDING_GENERATOR
[opencv 0.52.0] ===   BUILDTIME_BINDGEN
[opencv 0.52.0] ===   CLANG
[opencv 0.52.0] ===   DEFAULT
[opencv 0.52.0] ===   JOBSERVER
[opencv 0.52.0] ===   OPENCV_4
[opencv 0.52.0] === Detected probe priority based on environment vars: pkg_config: false, cmake: false, vcpkg: false
[opencv 0.52.0] === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
[opencv 0.52.0] === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
[opencv 0.52.0] === Probing OpenCV library using pkg_config
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_PATH
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
[opencv 0.52.0] cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
[opencv 0.52.0] cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[opencv 0.52.0] === OpenCV library configuration: Library {
[opencv 0.52.0]     include_paths: [
[opencv 0.52.0]         "/usr/local/Cellar/opencv/4.1.0_2/include/opencv4/opencv",
[opencv 0.52.0]         "/usr/local/Cellar/opencv/4.1.0_2/include/opencv4",
[opencv 0.52.0]     ],
[opencv 0.52.0]     version: "4.1.0",
[opencv 0.52.0]     cargo_metadata: [
[opencv 0.52.0]         "cargo:rustc-link-search=/usr/local/Cellar/opencv/4.1.0_2/lib",
[opencv 0.52.0]         "cargo:rustc-link-search=framework=/usr/local/Cellar/opencv/4.1.0_2/lib",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_gapi",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_stitching",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_aruco",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_bgsegm",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_bioinspired",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_ccalib",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_dnn_objdetect",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_dpm",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_face",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_freetype",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_fuzzy",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_hfs",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_img_hash",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_line_descriptor",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_quality",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_reg",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_rgbd",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_saliency",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_sfm",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_stereo",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_structured_light",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_phase_unwrapping",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_superres",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_optflow",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_surface_matching",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_tracking",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_datasets",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_text",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_dnn",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_plot",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_videostab",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_video",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_xfeatures2d",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_shape",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_ml",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_ximgproc",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_xobjdetect",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_objdetect",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_calib3d",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_features2d",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_highgui",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_videoio",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_imgcodecs",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_flann",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_xphoto",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_photo",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_imgproc",
[opencv 0.52.0]         "cargo:rustc-link-lib=opencv_core",
[opencv 0.52.0]     ],
[opencv 0.52.0] }
[opencv 0.52.0] === Found OpenCV library version: 4.1.0 in headers located at: /usr/local/Cellar/opencv/4.1.0_2/include/opencv4
[opencv 0.52.0] === Using OpenCV headers from: /usr/local/Cellar/opencv/4.1.0_2/include/opencv4/opencv2
[opencv 0.52.0] === Generating code in: /Library/Stacks/development/rust/workspace/sak_tools/target/debug/build/opencv-3324e9d88e23e78f/out
[opencv 0.52.0] === Placing generated bindings into: /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/bindings/rust/opencv_4
[opencv 0.52.0] === Clang: Apple clang version 11.0.3 (clang-1103.0.32.59)
[opencv 0.52.0] === Clang command line args: [
[opencv 0.52.0]     "-isystem/usr/local/include",
[opencv 0.52.0]     "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1",
[opencv 0.52.0]     "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include",
[opencv 0.52.0]     "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
[opencv 0.52.0]     "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
[opencv 0.52.0]     "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks",
[opencv 0.52.0]     "-I/usr/local/Cellar/opencv/4.1.0_2/include/opencv4",
[opencv 0.52.0]     "-I/Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/src_cpp",
[opencv 0.52.0]     "-DOCVRS_PARSING_HEADERS",
[opencv 0.52.0]     "-includeocvrs_ephemeral.hpp",
[opencv 0.52.0]     "-std=c++14",
[opencv 0.52.0] ]
[opencv 0.52.0] === WARNING: 1 diagnostic messages
[opencv 0.52.0] ===    /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/src_cpp/core.hpp:9:11: fatal error: 'opencv2/core/async.hpp' file not found
[opencv 0.52.0] thread '<unnamed>' panicked at '=== Errors during header parsing', /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-binding-generator-0.26.0/src/generator.rs:510:17
[opencv 0.52.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[opencv 0.52.0] === Generated: freetype
[opencv 0.52.0] === Generated: dpm
[opencv 0.52.0] === Generated: bgsegm
[opencv 0.52.0] === Generated: bioinspired
[opencv 0.52.0] === Generated: fuzzy
[opencv 0.52.0] === Generated: flann
[opencv 0.52.0] === Generated: aruco
[opencv 0.52.0] === Generated: ccalib
[opencv 0.52.0] === Generated: hfs
[opencv 0.52.0] === Generated: features2d
[opencv 0.52.0] === Generated: face
[opencv 0.52.0] === Generated: imgcodecs
[opencv 0.52.0] === Generated: highgui
[opencv 0.52.0] === Generated: img_hash
[opencv 0.52.0] === Generated: calib3d
[opencv 0.52.0] === Generated: line_descriptor
[opencv 0.52.0] === Generated: plot
[opencv 0.52.0] === Generated: phase_unwrapping
[opencv 0.52.0] === Generated: dnn
[opencv 0.52.0] === Generated: quality
[opencv 0.52.0] === Generated: photo
[opencv 0.52.0] === Generated: optflow
[opencv 0.52.0] === Generated: objdetect
[opencv 0.52.0] === Generated: ml
[opencv 0.52.0] === Generated: saliency
[opencv 0.52.0] === Generated: sfm
[opencv 0.52.0] === Generated: stereo
[opencv 0.52.0] === Generated: shape
[opencv 0.52.0] === Generated: imgproc
[opencv 0.52.0] === Generated: structured_light
[opencv 0.52.0] === Generated: superres
[opencv 0.52.0] thread 'main' panicked at 'Can't join thread: Any', /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/build_generator.rs:158:28
error: failed to run custom build command for `opencv v0.52.0`

Caused by:
  process didn't exit successfully: `/Library/Stacks/development/rust/workspace/sak_tools/target/debug/build/opencv-0af03f55ee6b47bf/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=OPENCV4_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENCV4_STATIC
  cargo:rerun-if-env-changed=OPENCV4_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  === Clang: Apple clang version 11.0.3 (clang-1103.0.32.59)

  --- stderr
  === Crate version: Some("0.52.0")
  === Environment configuration:
  ===   OPENCV_HEADER_DIR = None
  ===   OPENCV_PACKAGE_NAME = None
  ===   OPENCV_PKGCONFIG_NAME = None
  ===   OPENCV_CMAKE_NAME = None
  ===   OPENCV_CMAKE_BIN = None
  ===   OPENCV_VCPKG_NAME = None
  ===   OPENCV_LINK_LIBS = None
  ===   OPENCV_LINK_PATHS = None
  ===   OPENCV_INCLUDE_PATHS = None
  ===   OPENCV_DISABLE_PROBES = None
  ===   OPENCV_CLANG_STDLIB_PATH = None
  ===   OPENCV_MODULE_WHITELIST = None
  ===   OPENCV_MODULE_BLACKLIST = None
  ===   CMAKE_PREFIX_PATH = None
  ===   OpenCV_DIR = None
  ===   PKG_CONFIG_PATH = None
  ===   VCPKG_ROOT = None
  ===   VCPKGRS_DYNAMIC = None
  === Enabled features:
  ===   BINDING_GENERATOR
  ===   BUILDTIME_BINDGEN
  ===   CLANG
  ===   DEFAULT
  ===   JOBSERVER
  ===   OPENCV_4
  === Detected probe priority based on environment vars: pkg_config: false, cmake: false, vcpkg: false
  === Probing the OpenCV library in the following order: environment, pkg_config, cmake, vcpkg_cmake, vcpkg
  === Can't probe using: environment, continuing with other methods because: Some environment variables are missing
  === Probing OpenCV library using pkg_config
  === OpenCV library configuration: Library {
      include_paths: [
          "/usr/local/Cellar/opencv/4.1.0_2/include/opencv4/opencv",
          "/usr/local/Cellar/opencv/4.1.0_2/include/opencv4",
      ],
      version: "4.1.0",
      cargo_metadata: [
          "cargo:rustc-link-search=/usr/local/Cellar/opencv/4.1.0_2/lib",
          "cargo:rustc-link-search=framework=/usr/local/Cellar/opencv/4.1.0_2/lib",
          "cargo:rustc-link-lib=opencv_gapi",
          "cargo:rustc-link-lib=opencv_stitching",
          "cargo:rustc-link-lib=opencv_aruco",
          "cargo:rustc-link-lib=opencv_bgsegm",
          "cargo:rustc-link-lib=opencv_bioinspired",
          "cargo:rustc-link-lib=opencv_ccalib",
          "cargo:rustc-link-lib=opencv_dnn_objdetect",
          "cargo:rustc-link-lib=opencv_dpm",
          "cargo:rustc-link-lib=opencv_face",
          "cargo:rustc-link-lib=opencv_freetype",
          "cargo:rustc-link-lib=opencv_fuzzy",
          "cargo:rustc-link-lib=opencv_hfs",
          "cargo:rustc-link-lib=opencv_img_hash",
          "cargo:rustc-link-lib=opencv_line_descriptor",
          "cargo:rustc-link-lib=opencv_quality",
          "cargo:rustc-link-lib=opencv_reg",
          "cargo:rustc-link-lib=opencv_rgbd",
          "cargo:rustc-link-lib=opencv_saliency",
          "cargo:rustc-link-lib=opencv_sfm",
          "cargo:rustc-link-lib=opencv_stereo",
          "cargo:rustc-link-lib=opencv_structured_light",
          "cargo:rustc-link-lib=opencv_phase_unwrapping",
          "cargo:rustc-link-lib=opencv_superres",
          "cargo:rustc-link-lib=opencv_optflow",
          "cargo:rustc-link-lib=opencv_surface_matching",
          "cargo:rustc-link-lib=opencv_tracking",
          "cargo:rustc-link-lib=opencv_datasets",
          "cargo:rustc-link-lib=opencv_text",
          "cargo:rustc-link-lib=opencv_dnn",
          "cargo:rustc-link-lib=opencv_plot",
          "cargo:rustc-link-lib=opencv_videostab",
          "cargo:rustc-link-lib=opencv_video",
          "cargo:rustc-link-lib=opencv_xfeatures2d",
          "cargo:rustc-link-lib=opencv_shape",
          "cargo:rustc-link-lib=opencv_ml",
          "cargo:rustc-link-lib=opencv_ximgproc",
          "cargo:rustc-link-lib=opencv_xobjdetect",
          "cargo:rustc-link-lib=opencv_objdetect",
          "cargo:rustc-link-lib=opencv_calib3d",
          "cargo:rustc-link-lib=opencv_features2d",
          "cargo:rustc-link-lib=opencv_highgui",
          "cargo:rustc-link-lib=opencv_videoio",
          "cargo:rustc-link-lib=opencv_imgcodecs",
          "cargo:rustc-link-lib=opencv_flann",
          "cargo:rustc-link-lib=opencv_xphoto",
          "cargo:rustc-link-lib=opencv_photo",
          "cargo:rustc-link-lib=opencv_imgproc",
          "cargo:rustc-link-lib=opencv_core",
      ],
  }
  === Found OpenCV library version: 4.1.0 in headers located at: /usr/local/Cellar/opencv/4.1.0_2/include/opencv4
  === Using OpenCV headers from: /usr/local/Cellar/opencv/4.1.0_2/include/opencv4/opencv2
  === Generating code in: /Library/Stacks/development/rust/workspace/sak_tools/target/debug/build/opencv-3324e9d88e23e78f/out
  === Placing generated bindings into: /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/bindings/rust/opencv_4
  === Clang command line args: [
      "-isystem/usr/local/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include",
      "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include",
      "-isystem/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
      "-isystem/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks",
      "-I/usr/local/Cellar/opencv/4.1.0_2/include/opencv4",
      "-I/Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/src_cpp",
      "-DOCVRS_PARSING_HEADERS",
      "-includeocvrs_ephemeral.hpp",
      "-std=c++14",
  ]
  === WARNING: 1 diagnostic messages
  ===    /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/src_cpp/core.hpp:9:11: fatal error: 'opencv2/core/async.hpp' file not found
  thread '<unnamed>' panicked at '=== Errors during header parsing', /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-binding-generator-0.26.0/src/generator.rs:510:17
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  === Generated: freetype
  === Generated: dpm
  === Generated: bgsegm
  === Generated: bioinspired
  === Generated: fuzzy
  === Generated: flann
  === Generated: aruco
  === Generated: ccalib
  === Generated: hfs
  === Generated: features2d
  === Generated: face
  === Generated: imgcodecs
  === Generated: highgui
  === Generated: img_hash
  === Generated: calib3d
  === Generated: line_descriptor
  === Generated: plot
  === Generated: phase_unwrapping
  === Generated: dnn
  === Generated: quality
  === Generated: photo
  === Generated: optflow
  === Generated: objdetect
  === Generated: ml
  === Generated: saliency
  === Generated: sfm
  === Generated: stereo
  === Generated: shape
  === Generated: imgproc
  === Generated: structured_light
  === Generated: superres
  thread 'main' panicked at 'Can't join thread: Any', /Users/donny/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/opencv-0.52.0/build_generator.rs:158:28

**Comment by twistedfall** [comment] 2021-04-15 07:30
Do you absolutely must use the 4.1.0 OpenCV version? The problem is that this version doesn't have the `opencv2/core/async.hpp` header which I include unconditionally. If you can update that would be the fastest solution to the problem, latest version (4.5.2) would be the best, but even 4.1.1 would fix that issue (it has the opencv2/core/async.hpp). I will release the fix for that issue anyway, but it will take a bit.

**Comment by yang-dong-dong** [comment] 2021-04-16 08:24
Thanks

**Comment by twistedfall** [comment] 2021-04-16 21:18
This has now been fixed in the v0.53.0, please check the [changelog](https://github.com/twistedfall/opencv-rust/blob/master/CHANGES.md) too.

**Closed as completed by twistedfall** 2021-04-16 21:18 UTC
